# see: https://prettier.io/docs/options
# see: https://prettier.io/docs/configuration
semi: false

# Special rules.
# see: https://prettier.io/docs/configuration#configuration-overrides
# see: https://prettier.io/docs/option-philosophy
overrides:
  - { files: "*.jsonc", options: { trailingComma: "none" } }
